version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: temperaturecontrol-sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong@Password123
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql
    networks:
      - temperaturecontrol-network
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "YourStrong@Password123" -Q "SELECT 1" || exit 1
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s

  redis:
    image: redis:7-alpine
    container_name: temperaturecontrol-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - temperaturecontrol-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: temperaturecontrol-api
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=TemperatureControlDB;User Id=sa;Password=YourStrong@Password123;TrustServerCertificate=True;
      - ConnectionStrings__Redis=redis:6379
      - JWT__Secret=YourSuperSecretKeyForJWTTokenGenerationMinimum32Characters
      - JWT__Issuer=TemperatureControlAPI
      - JWT__Audience=TemperatureControlClient
      - JWT__ExpirationMinutes=60
      - CORS__AllowedOrigins__0=http://localhost:3000
      - CORS__AllowedOrigins__1=http://localhost:5173
    depends_on:
      sqlserver:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - temperaturecontrol-network
    restart: unless-stopped

volumes:
  sqlserver-data:
    driver: local
  redis-data:
    driver: local

networks:
  temperaturecontrol-network:
    driver: bridge
