name: Backend CI/CD

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'backend/**'
      - '.github/workflows/backend-ci.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'backend/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore backend/TemperatureControl.sln

    - name: Build
      run: dotnet build backend/TemperatureControl.sln --configuration Release --no-restore

    - name: Run tests
      run: dotnet test backend/TemperatureControl.sln --configuration Release --no-build --verbosity normal --collect:"XPlat Code Coverage"

    - name: Upload coverage reports
      uses: codecov/codecov-action@v3
      with:
        files: '**/coverage.cobertura.xml'
        flags: backend

  docker-build:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run: |
        cd backend
        docker build -t temperature-control-api:latest .

    - name: Save Docker image
      run: docker save temperature-control-api:latest | gzip > backend-image.tar.gz

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: backend-docker-image
        path: backend-image.tar.gz
        retention-days: 7
